# Backend configuration for storing Terraform state in Azure Storage
# Note: This file is automatically generated/updated by the GitHub Actions workflow
# For local testing, the test-backend-setup-locally.sh script will update this file
# Do not manually edit - it will be overwritten

terraform {
  backend "azurerm" {
    # Configuration is injected dynamically by:
    # - GitHub Actions workflow (deploy-azure-infrastructure.yml)
    # - Local testing script (test-backend-setup-locally.sh)
    #
    # Values set at runtime:
    # resource_group_name  = "testcontainers-tfstate-rg"
    # storage_account_name = "tctfstate{subscription-id-first-8}"
    # container_name       = "{environment-tag}"
    # key                  = "terraform.tfstate"
    # use_oidc             = true (GitHub Actions only)
  }
}
